baseURL: "https://fairness.coop/"
languageCode: "fr-FR"
title: "Fairness"
params:
  tagline: "Concevoir responsable"
paginate: 5

menu:
  main:
  - identifier: contact
    name: Contactez nous
    url: 
  - identifier: coop
    name: La coopérative
    url: /blog/2019/creation-cooperative-conception-responsable/


