baseURL: 'https://fairness.coop/'
languageCode: 'fr-FR'
title: 'Fairness'
params:
  tagline: 'Concevoir responsable'
paginate: 5

menu:
  main:
    - identifier: contact
      name: Contactez nous
      url: mailto:equipe(at)fairness.coop
    - identifier: coop
      name: La coopérative
      url: /blog/2019/creation-cooperative-conception-responsable/
    - identifier: equipe
      name: L'équipe
      url: /team/
    - identifier: notre-offre
      name: Notre offre
      url: /blog/2019/notre-offre/
    - identifier: nos-references
      name: Nos références
      url: /blog/2019/references/
    - identifier: blog
      name: Blog
      url: /blog/
    - identifier: podcast-echo
      name: Podcast echo
      url: https://podcastecho.github.io/
    - identifier: podcast-techologie
      name: Podcast techologie
      url: https://techologie.net/
    - identifier: legal
      name: Mentions légales
      url: /legal/

markup:
  defaultMarkdownHandler: blackfriday
  highlight:
    codeFences: true
    guessSyntax: false
    hl_Lines: ''
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4

related:
  indices:
    - name: authorId # The name of the indice, same as Front Matter's .Param key.
      weight: 1 # We don't really need this, but omitting it would disable the indice.
      includeNewer: true # Here our relationship is timeless! This prevents Hugo from ignoring newer posts.